export const REGISTER_DELIVERY_SUCCESS="REGISTER_DELIVERY_SUCCESS";
export const REGISTER_DELIVERY_FAILURE="REGISTER_DELIVERY_FAILURE";
export const REGISTER_DELIVERY="REGISTER_DELIVERY";
export const REQUEST_DELIVERIES = "REQUEST_DELIVERIES";
export const REQUEST_DELIVERIES_SUCCESS="REQUEST_DELIVERIES_SUCCESS";