export const REGISTER_PACKAGE_SUCCESS="REGISTER_PACKAGE_SUCCESS";
export const DELETE_PACKAGE="DELETE_PACKAGE";
export const DELETE_PACKAGE_FAILURE="DELETE_PACKAGE_FAILURE";
export const REGISTER_PACKAGE_FAILURE="REGISTER_PACKAGE_FAILURE";
export const REGISTER_PACKAGE="REGISTER_PACKAGE"