export const USER_SET = "USER_SET";
export const USER_UNSET = "USER_UNSET";
export const REGISTER_USER="REGISTER_USER";
export const REGISTER_USER_SUCCESS="REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAILURE="REGISTER_USER_FAILURE";
export const HIDE_MESSAGE="HIDE_MESSAGE";
